### Print 
print_tro:  0
print_yaml: 0
print_filter: ba
# b -> basic
# B -> basic+
# + -> additionnal
# d -> density
# r -> reading
# R -> reading+
# p -> pattern
# a -> accuracy
# * -> star
print_order: FDRPA
# F -> final
# D -> density
# R -> reading
# P -> pattern
# A -> accuracy

### Others
mods: __
# no space between mods (ex: DTHR), use __ for no mod
flat: 0
# change D to d, etc
no_bonus: 0
# remove bonus objects

### osux db
osuxdb_path:     ./osuxdb
osuxdb_build:    0
osuxdb_song_dir: ./bb_maps/

### Database
database:  0
db_ip:     localhost
db_login:  root
db_passwd: NOPE

### Score
score:        1
score_quick:  1
score_method: 0
# 0 -> hardest
# 1 -> best influence
score_input:  1
# 0 -> acc
# 1 -> good and miss
score_acc:  100
score_good: 0
score_miss: 5

# About score_methods:
# quick is way less accurate
#    I'm your daddy [Kantan]
#    quick  + hardest 90% ~= normal + hardest 95%
# hardest is less accurate but ok 
#    I'm your daddy [Kantan]
#    normal + hardest 90% ~= normal + best influence 91%
