# 
database:    0
print_tro:   0
print_yaml:  0
print_order: FDRPA
# F -> final
# D -> density
# R -> reading
# P -> pattern
# A -> accuracy

db_ip:     localhost
db_login:  root
db_passwd: nope

score_acc: 0.95