# 
print_tro:   0
print_yaml:  0
print_order: FDRPA
# F -> final
# D -> density
# R -> reading
# P -> pattern
# A -> accuracy

# Database
database:    0
db_ip:     localhost
db_login:  root
db_passwd: nope

# Score
score: 0
score_acc: 0.95
score_method: 0
# 0 -> hardest
# 1 -> best influence